### ISSUE TITLE
sircel integration?

### ISSUE THREAD

**Issue by colindaven** [Hoohm/dropSeqPipe#74]
Dear dropseq users,

I have seen quite a few dropseq pipe outputs - which is a very nice tool by the way - which have a dropout of 50-75% of total sequences due to both cell and UMI barcode errors. 

Apparently this is a known phenomenon, and is the reason why the sircel barcode corrector has been created.
https://github.com/pachterlab/sircel

My questions then - is sircel decent - I have results but haven't checked them so far, and b, is there a way to plug them into the dropseqpipe pipeline, which is pretty essential for me so far.

Sircel produces results per cell barcode as separate FASTQs.
Example

```
-r-- 1 rcug rcug     88623 Feb  8 02:16 cell_TTTTTAAGCAGT.umi.txt
-rw-rw-r-- 1 rcug rcug    161919 Feb  8 00:28 cell_TTTTTCATGGCC_barcodes.fastq.gz
-rw-rw-r-- 1 rcug rcug    381134 Feb  8 00:28 cell_TTTTTCATGGCC_reads.fastq.gz
-rw-rw-r-- 1 rcug rcug     90414 Feb  8 00:28 cell_TTTTTCATGGCC.umi.txt
-rw-rw-r-- 1 rcug rcug    211083 Feb  8 01:09 cell_TTTTTTGACATT_barcodes.fastq.gz
-rw-rw-r-- 1 rcug rcug    491631 Feb  8 01:09 cell_TTTTTTGACATT_reads.fastq.gz
-rw-rw-r-- 1 rcug rcug    117468 Feb  8 01:09 cell_TTTTTTGACATT.umi.txt
-rw-rw-r-- 1 rcug rcug    232076 Feb  8 00:20 cell_TTTTTTTAAGCA_barcodes.fastq.gz
-rw-rw-r-- 1 rcug rcug    476822 Feb  8 00:20 cell_TTTTTTTAAGCA_reads.fastq.gz
-rw-rw-r-- 1 rcug rcug    140616 Feb  8 00:20 cell_TTTTTTTAAGCA.umi.txt

```

Would be grateful for any hints.

Colin

**Comment by Hoohm** [comment]
Hello @colindaven and sorry for the long wait. You've slipped by my attention.

Could you please expand on the premise of your question. Why are the cell/umi barcodes error a problem for you? dropSeqPipe does cell and umi correction (cell barcode for 1 error and umi based on dropseq_Tools)

Now to answer your questions:

A) Last time I've tried Sircel, about 1 year ago, it was super slow on large datasets such as 10x so I didn't run it since then. I've seen that they are working on something new that might be interesting to test, it's called [kite](https://github.com/pachterlab/kite).
B) Plugging your actual results into dropSeqPipe is possible. I would cat all cell/umi fastq together and all reads together. Those would be the actual inputs of dropSeqPipe. You can use your whitelist also since you already know which cells you want to keep.

I hope this helps. If you're looking for alternatives, I would also look into [umi_tools](https://github.com/CGATOxford/UMI-tools) or maybe [Alevin](https://salmon.readthedocs.io/en/latest/alevin.html)

I'm keen on answering more precisely if you have followup questions. :)

**Comment by colindaven** [comment]
Hi @Hoohm 

thanks for your thoughtful answer.

The dropouts from both cell and umi errors are problem because I am losing 50-75% of my data before I even get to the alignment stage. That's an issue when just starting with 400m NextSeq reads, since the sensitivity is then very low. Unfortunately there is resistance to using a bigger off-site sequencer.

I am glad to see dropseq does perform barcode correction, yet still see poor results (which is of course due to the poor data quality). I was hoping to test sircel's ability to rescue this.

I will attempt to plug results into dropSeqPipe, thanks for your confirmation that this may work.

You're right, it was slow, but using a cluster is was manageable for the small datasets I have here. 

Incidentally, what do you see an acceptable range of cell, UMI and both dropouts using dropseq datasets ? 10X genomics data is far more expensive, but seems far better thus far from what I've seen.
